# Generated by Django 5.2.11 on 2026-03-10 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Редактирование'), ('delete', 'Удаление'), ('login', 'Вход'), ('logout', 'Выход'), ('login_failed', 'Неудачный вход'), ('search', 'Поиск'), ('view', 'Просмотр'), ('filter', 'Фильтрация')], max_length=20, verbose_name='Действие')),
                ('model_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Модель')),
                ('object_id', models.CharField(blank=True, default='', max_length=50, verbose_name='ID объекта')),
                ('object_repr', models.CharField(blank=True, default='', max_length=255, verbose_name='Представление')),
                ('details', models.TextField(blank=True, default='', verbose_name='Детали')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата/время')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='auditlog_au_user_id_f1faf1_idx'), models.Index(fields=['action', '-timestamp'], name='auditlog_au_action_67751c_idx'), models.Index(fields=['model_name', '-timestamp'], name='auditlog_au_model_n_9812b4_idx')],
            },
        ),
    ]
