# Generated by Django 5.2.11 on 2026-03-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Создание'), ('update', 'Редактирование'), ('delete', 'Удаление'), ('login', 'Вход'), ('logout', 'Выход'), ('login_failed', 'Неудачный вход'), ('search', 'Поиск'), ('view', 'Просмотр'), ('filter', 'Фильтрация'), ('export', 'Экспорт')], max_length=20, verbose_name='Действие'),
        ),
    ]
