# Generated by Django 5.2.11 on 2026-03-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_alter_object_association_alter_object_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(default='', max_length=300, verbose_name='Название'),
        ),
    ]
