# Generated by Django 5.2.11 on 2026-03-06 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='references.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='forcekind',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='force_kinds', to='references.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='forcetype',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='force_types', to='references.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='govorg',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gov_orgs', to='references.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='unit',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='references.country', verbose_name='Страна'),
        ),
    ]
